services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: mirkayk
      POSTGRES_PASSWORD: mirkayk_dev
      POSTGRES_DB: mirkayk
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
